version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16
    commands:
      - npm install

  post_build:
    commands:
      # Package the code into a ZIP file
      - zip -r mylambdafunction.zip .

      # AWS CLI command to invoke the Lambda function with the ZIP file as payload
      - aws lambda update-function-code --function-name storeNews --zip-file fileb://mylambdafunction.zip

source:
  location: backend/scrapper