version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16
    commands:
      - cd backend/scrapper
      - npm install

  post_build:
    commands:
      # Create a temporary directory to stage the files
      - mkdir staging

      # Copy only the relevant files to the staging directory
      - cp -r backend/scrapper/* staging/

      # Package the code into a ZIP file
      - zip -r mylambdafunction.zip staging

      # AWS CLI command to invoke the Lambda function with the ZIP file as payload
      - aws lambda update-function-code --function-name storeNews --zip-file fileb://mylambdafunction.zip
    
      # Clean up
      - rm -rf staging