version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 16
    commands:
      - cd backend/api
      - npm install --production

  post_build:
    commands:
      # Package the code into a ZIP file
      - zip -r mylambdafunction.zip .

      # AWS CLI command to update the Lambda function code with the ZIP file
      - aws lambda update-function-code --function-name getNews --zip-file fileb://mylambdafunction.zip --debug